spring:
  config:
    import: application.yml
app:
  database:
    url: ${APP_DATABASE_URL}
    username: ${APP_DATABASE_USERNAME}
    password: ${APP_DATABASE_PASSWORD}
  security.jwt:
    tokenSecret: ${APP_JWT_TOKEN_SECRET}