app:
  database:
    url: jdbc:postgresql://46.101.167.158:5432/maciek_dev
    username: postgres
    password: postgres
  security.jwt:
    tokenSecret: secret
    tokenExpirationAfterSeconds: 604800
    tokenIssuer: http://localhost:8080

spring:
  datasource:
    url: ${app.database.url}
    username: ${app.database.username}
    password: ${app.database.password}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    url: ${app.database.url}
    user: ${app.database.username}
    password: ${app.database.password}
  jpa:
    hibernate:
      ddl-auto: validate

context.initializer.classes: com.zam.interactivelearning.application.configuration.BeansInitializer
