app:
  database:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  security.jwt:
    tokenSecret: secret
    tokenExpirationAfterSeconds: 3600
    tokenIssuer: http://localhost:8080

spring:
  datasource:
    url: ${app.database.url}
    username: ${app.database.username}
    password: ${app.database.password}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    url: ${app.database.url}
    user: ${app.database.username}
    password: ${app.database.password}
  jpa:
    hibernate:
      ddl-auto: validate

context.initializer.classes: com.zam.interactivelearning.application.configuration.BeansInitializer

logging.level:
  com.maciekbartczak: DEBUG
