CREATE TABLE USER_FRIENDS(
    USER_ID BIGINT NOT NULL,
    FRIEND_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (FRIEND_ID) REFERENCES USERS(ID),
    UNIQUE (USER_ID, FRIEND_ID)
);