CREATE SEQUENCE notification_templates_id_seq;
CREATE TABLE NOTIFICATION_TEMPLATES(
    ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('notification_templates_id_seq'),
    NOTIFICATION_NAME VARCHAR(255) NOT NULL,
    NOTIFICATION_TEMPLATE VARCHAR(500) NOT NULL
);