CREATE SEQUENCE quiz_scores_id_seq;
CREATE TABLE QUIZ_SCORES(
    ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('quiz_scores_id_seq'),
    USER_ID BIGINT NOT NULL REFERENCES users(id),
    QUIZ_ID BIGINT NOT NULL REFERENCES quizzes(id),
    SCORE INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
)