CREATE TABLE USER_ROLES(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,

    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID),
    UNIQUE (USER_ID, ROLE_ID)
)