CREATE SEQUENCE questions_id_seq;
CREATE TABLE QUESTIONS
(
    ID         BIGINT PRIMARY KEY DEFAULT nextval('questions_id_seq'),
    CONTENT    VARCHAR(250) NOT NULL,
    QUIZ_ID    BIGINT       NOT NULL REFERENCES QUIZZES (ID),
    CREATED_BY BIGINT       NOT NULL REFERENCES USERS (ID)
);