CREATE SEQUENCE answers_id_seq;
CREATE TABLE ANSWERS
(
    ID          BIGINT PRIMARY KEY DEFAULT nextval('answers_id_seq'),
    CONTENT     VARCHAR(250) NOT NULL,
    QUESTION_ID BIGINT       NOT NULL REFERENCES QUESTIONS (ID),
    IS_CORRECT  BOOLEAN      NOT NULL,
    CREATED_BY  BIGINT       NOT NULL REFERENCES USERS (ID)
);