CREATE SEQUENCE flashcards_id_seq;
CREATE TABLE FLASHCARDS
(
    ID         BIGINT PRIMARY KEY DEFAULT nextval('flashcards_id_seq'),
    CONTENT    VARCHAR(250) NOT NULL,
    ANSWER     VARCHAR(250) NOT NULL,
    CREATED_BY BIGINT       NOT NULL REFERENCES USERS (ID)
);