// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGQUYiDRN-iiAUMjEgyaddMRTEekAYNYA',
    appId: '1:958745155224:web:8177e98f31cbfd3570e2ed',
    messagingSenderId: '958745155224',
    projectId: 'interactive-learning-10460',
    authDomain: 'interactive-learning-10460.firebaseapp.com',
    storageBucket: 'interactive-learning-10460.appspot.com',
    measurementId: 'G-8S8WQ6X7YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV1f8RYLv_5VkILxxVDapR8s0J21YP3DY',
    appId: '1:958745155224:android:86c43af0bbf6689e70e2ed',
    messagingSenderId: '958745155224',
    projectId: 'interactive-learning-10460',
    storageBucket: 'interactive-learning-10460.appspot.com',
  );
}
