name: Build backend project
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install
      - name: Persist test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./backend/application/target/surefire-reports
      - name: Generate api specification
        run: |
          cd application
          mvn springdoc-openapi:generate
      - name: Persist specification file
        uses: actions/upload-artifact@v2
        with:
          name: apispec
          path: .application/target/apispec.json

  build-mobile:
    needs: build-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Download api specification
        uses: actions/download-artifact@v2
        with:
          name: apispec
          path: ./apispec
      - name: Setup application
        run: ./setup.sh ./apispec/apispec.json
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
      - run: flutter build apk

  generate-report:
    needs: build-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: ./backend/application/target/surefire-reports
      - name: Publish test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test report
          path: "**/surefire-reports/TEST-*.xml"
          reporter: java-junit