name: Build application
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install
      - name: Persist test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./backend/application/target/surefire-reports
      - name: Persist specification file
        uses: actions/upload-artifact@v3
        with:
          name: apispec
          path: ./backend/application/target/apispec.json

  generate-report:
    needs: build-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: ./backend/application/target/surefire-reports
      - name: Publish test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test report
          path: "**/surefire-reports/TEST-*.xml"
          reporter: java-junit