name: Build application
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install
      - name: Persist specification file
        uses: actions/upload-artifact@v3
        with:
          name: apispec
          path: ./backend/application/target/apispec.json
      - name: Persist test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./backend/**/target/surefire-reports

  generate-report:
    needs: build-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: ./test-results
      - name: Publish test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test report
          path: "**/surefire-reports/TEST-*.xml"
          reporter: java-junit
  generate-api-client:
    needs: build-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Download api specification
        uses: actions/download-artifact@v2
        with:
          name: apispec
      - name: Generate api client
        run: ./setup.sh ../apispec.json ./api-client
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update api client
          branch: generated-api-client
          file_pattern: ./mobile/api-client/*
          disable_globbing: true
          add_options: -f
          commit_user_name: Interactive Learning Actions
          create_branch: true